Repository bitwarden/web, pull requests merged in 2022-02, with the labels that each got.

#1435 [Icons] FF - requested icon changes
  package-lock.json
  package.json
  src/app/organizations/vault/vault.component.html
  src/app/send/send.component.html
  src/app/vault/add-edit.component.html
  src/app/vault/bulk-actions.component.html
  src/app/vault/ciphers.component.html
  src/app/vault/groupings.component.html
  src/app/vault/vault.component.html
  webpack.config.js
Labels: enhancement

#1443 [Icons] Fix button icon/text margins
  src/app/organizations/vault/vault.component.html
  src/app/send/send.component.html
  src/app/vault/ciphers.component.html
  src/app/vault/vault.component.html
  src/scss/base.scss
Labels: bug

#1482 Create initial workflow
  .github/workflows/workflow-linter.yml
Labels: DevOps

#1487 [Icons Bug] fa-remove -> bwi-close
  bitwarden_license/src/app/providers/manage/people.component.html
  src/app/settings/emergency-access.component.html
Labels: bug

#1497 Added dry run logic
  .github/workflows/release.yml
Labels: DevOps
